server:
  port: 8300
spring:
  application:
    name: reservation-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    url: jdbc:postgresql://animal-hotel-reservation-postgres:5432/reservationdb
    username: postgres
    password: postgres
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

logging:
  level:
    pl.altkom.animalhotel.reservationservice.client: DEBUG
feign:
  client:
    config:
      default:
        loggerLevel: full
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
